accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('edit/<int:pk>', views.AccountUpdate.as_view(), name='account_update'),
    path('change_password', views.change_password, name='change_password'),
]

books/urls.py
from django.urls import path

from . import views

app_name = 'books'
urlpatterns = [
    path('', views.BooksIndex.as_view(), name='index'),
    path('libraries', views.LibrariesList.as_view(), name='libraries'),
    path('library/<int:pk>/', views.LibraryDetail.as_view(), name='library_detail'),
    path('library/<int:pk>/book_add', views.book_add, name='book_add'),
    path('library/<int:pk>/shelf_add', views.shelf_add, name='shelf_add'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('copy_delete/<int:pk>/', views.BookCopyDelete.as_view(), name='copy_delete'),
    path('copy_move/<int:pk>/', views.copy_move, name='copy_move'),
    path('shelf_delete/<int:pk>/', views.ShelfDelete.as_view(), name='shelf_delete'),
    path('shelf_rename/<int:pk>/', views.shelf_rename, name='shelf_rename'),
    path('book_update/<int:pk>/', views.BookUpdate.as_view(), name='book_update'),
]

llibres/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.conf import settings

urlpatterns = [
    path('books/', include('books.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/books/', permanent=False), name='index')
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

llibres/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Llibres{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'books/css/mystyles.css' %}">
        <script type="text/javascript"> (function() { var css = document.createElement('link'); css.href = 'https://use.fontawesome.com/releases/v5.1.0/css/all.css'; css.rel = 'stylesheet'; css.type = 'text/css'; document.getElementsByTagName('head')[0].appendChild(css); })(); </script>
        <!-- <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script> -->
        {% block extra_scripts %}{% endblock %}
    </head>
    <body>
        <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                {% if user.is_authenticated %}
                <a href="{% url 'books:libraries' %}" class="navbar-item">
                    Llibres
                </a>
                {% else %}
                <a href="{% url 'books:index' %}" class="navbar-item">
                    Llibres
                </a>
                {% endif %}
                <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarTop" onclick="document.getElementById('navbarTop').classList.toggle('is-active')">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
            <div class="navbar-menu is-hidden-touch">
                <div class="navbar-end">
                    {% if user.is_authenticated %}
                        <a class="navbar-item" href="{% url 'accounts:account_update' user.pk %}">{{ user.first_name }}</a>
                        <a class="navbar-item" href="{% url 'logout' %}">
                            <span class="icon is-small is-right">
                                <i class="fas fa-sign-out-alt"></i>
                            </span>
                        </a>
                    {% else %}
                        <a class="navbar-item" href="{% url 'login' %}">Log in</a>
                        <a class="navbar-item" href="{% url 'accounts:signup' %}">Sign up</a>
                    {% endif %}
                </div>
            </div>
            <div id="navbarTop" class="navbar-menu is-hidden-desktop">
                <div class="navbar-end">
                    {% if user.is_authenticated %}
                    <div class="navbar-item">
                        <div class="has-text-weight-bold">{{ user.first_name }}</div>
                        <a class="navbar-item" href="{% url 'accounts:account_update' user.pk %}">Account</a>
                        <a class="navbar-item" href="{% url 'logout' %}">Log out</a>
                    </div>
                    {% else %}
                        <a class="navbar-item" href="{% url 'login' %}">Log in</a>
                        <a class="navbar-item" href="{% url 'accounts:signup' %}">Sign up</a>
                        {% endif %}
                </div>
            </div>
        </nav>
        <div style="display: flex; min-height: 100vh; flex-direction: column;">
            <div id="content" style="flex: 1;">
                {% block content %}{% endblock %}
            </div>
                <footer class="footer">
                    <p>
                    <strong>Llibres</strong> by <a href="mailto:flg@tuta.io">Ferran López</a>. This web app is free software licensed under <a href="https://www.gnu.org/licenses/agpl-3.0.html">AGPL v3</a>. You can find the source code at <a href="https://gitlab.com/flopgui/llibres">GitLab</a>.
                    </p>
                </footer>
        </div>
    </body>
</html>