accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('edit/<int:pk>', views.AccountUpdate.as_view(), name='account_update'),
    path('change_password', views.change_password, name='change_password'),
]

books/urls.py
from django.urls import path

from . import views

app_name = 'books'
urlpatterns = [
    path('', views.BooksIndex.as_view(), name='index'),
    path('libraries', views.LibrariesList.as_view(), name='libraries'),
    path('library/<int:pk>/', views.LibraryDetail.as_view(), name='library_detail'),
    path('library/<int:pk>/book_add', views.book_add, name='book_add'),
    path('library/<int:pk>/shelf_add', views.shelf_add, name='shelf_add'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('copy_delete/<int:pk>/', views.BookCopyDelete.as_view(), name='copy_delete'),
    path('copy_move/<int:pk>/', views.copy_move, name='copy_move'),
    path('shelf_delete/<int:pk>/', views.ShelfDelete.as_view(), name='shelf_delete'),
    path('shelf_rename/<int:pk>/', views.shelf_rename, name='shelf_rename'),
    path('book_update/<int:pk>/', views.BookUpdate.as_view(), name='book_update'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(max_length=254, unique=True, blank=False)
    first_name = models.CharField(max_length=30, blank=False)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User

class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username','first_name','email','password1','password2')

accounts/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from .forms import SignUpForm
from .models import User


class SignUp(generic.CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'


class AccountUpdate(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    template_name = 'accounts/account_update.html'
    model = User
    fields = ['first_name', 'email']
    success_message = 'Profile updated'

    def get_success_url(self):
        return reverse('accounts:account_update', args=[self.object.pk])


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {
        'form': form
    })

accounts/templates/accounts/account_update.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Update profile{% endblock %}

{% block content %}
<section class="section">
    <h1 class="title">Update profile</h1>
    {% if messages %}
    {% for message in messages %}
    {% if message.tags == 'success' %}
    <article class="message is-success"><div class="message-body">{{ message }}</div></article>
    {% elif message.tags == 'error' %}
    <article class="message is-danger"><div class="message-body">{{ messag }}</div></article>
    {% else %}
    <article class="message is-info"><div class="message-body">{{ message }}</div></article>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% if form.errors %}
    <article class="message is-danger">
        <div class="message-body">
            {% for key, error in form.errors.items %}
            {{ error }}
            {% endfor %}
        </div>
    </article>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <fieldset disabled>
            <div class="field">
                <label class="label"> Username </label>
                <div class="control">
                    <input class="input" type="input" value="{{ user.username }}">
                </div>
            </div>
        </fieldset><br>
        <div class="field">
            <label class="label"> {{ form.first_name.label }} </label>
            <div class="control">
                {{ form.first_name|add_class:"input" }}
            </div>
        </div>
        <div class="field">
            <label class="label"> {{ form.email.label }} </label>
            <div class="control">
                {{ form.email|add_class:"input" }}
            </div>
        </div>
        <div class="field">
            <label class="label"> {{ form.password1.label }} </label>
            <div class="control">
                {{ form.password1|add_class:"input" }}
            </div>
        </div>
        <div class="field">
            <label class="label"> {{ form.password2.label }} </label>
            <div class="control">
                {{ form.password2|add_class:"input" }}
            </div>
        </div>
        <div class="field">
            <a class="button" href="{% url 'accounts:change_password' %}">Change password</a><br>
        </div>
        <div class="field">
            <button class="button is-primary" type="submit">Update</button>
        </div>
    </form>
</section>
{% endblock %} 

accounts/templates/accounts/change_password.html
{% extends 'base.html' %} 

{% load widget_tweaks %}

{% block content %}
<section class="section">
    {% if form.errors %}
    <article class="message is-danger">
        <div class="message-body">
            {% for key, error in form.errors.items %}
            {{ error }}
            {% endfor %}
        </div>
    </article>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="field">
            <label class="label"> {{ form.old_password.label }} </label>
            <div class="control">
                {{ form.old_password|add_class:"input" }}
            </div>
        </div>
        <div class="field">
            <label class="label"> {{ form.new_password1.label }} </label>
            <div class="control">
                {{ form.new_password1|add_class:"input" }}
            </div>
        </div>
        <article class="message is-info">
            <div class="message-body">
                {{ form.new_password1.help_text }}
            </div>
        </article>
        <div class="field">
            <label class="label"> {{ form.new_password2.label }} </label>
            <div class="control">
                {{ form.new_password2|add_class:"input" }}
            </div>
        </div>
        <button class="button is-primary" type="submit">Save</button>
    </form>
</section>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <section class="section">
    <h1 class="title">Sign up</h1>
    {% if form.errors %}
        <article class="message is-danger">
        <div class="message-body">
            {% for key, error in form.errors.items %}
            {{ error }}
            {% endfor %}
        </div>
        </article>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="field">
            <label class="label"> {{ form.username.label }} </label>
            <div class="control">
                {{ form.username|add_class:"input" }}
            </div>
        </div>
        <div class="field">
            <label class="label"> {{ form.first_name.label }} </label>
            <div class="control">
                {{ form.first_name|add_class:"input" }}
            </div>
        </div>
        <div class="field">
            <label class="label"> {{ form.email.label }} </label>
            <div class="control">
                {{ form.email|add_class:"input" }}
            </div>
        </div>
        <div class="field">
            <label class="label"> {{ form.password1.label }} </label>
            <div class="control">
                {{ form.password1|add_class:"input" }}
            </div>
        </div>
        <div class="field">
            <label class="label"> {{ form.password2.label }} </label>
            <div class="control">
                {{ form.password2|add_class:"input" }}
            </div>
        </div>
        <button class="button is-primary" type="submit">Sign up</button>
    </form>
    </section>
{% endblock %} 